### ISSUE TITLE
Fehler in Contao 4.11.x

### ISSUE THREAD

**Issue by jankout** [xprojects-de/alpdesk-parallax#23]
Hallo, 

bei mir kommt folgende Fehlermeldung, wenn ich bei einem Textlement die Animation aktiviere. Danach kann man sich die Seite gar nicht mehr anschauen. 

Es läuft mit Contao 4.11.1 und PHP 7.4.x

`[2021-03-23T17:45:21.880918+01:00] request.CRITICAL: Uncaught PHP Exception TypeError: "array_filter() expects parameter 1 to be array, null given" at /mnt/web302/b1/77/57048277/htdocs/contao/production/contao4/vendor/alpdesk/alpdesk-parallax/src/Listener/HooksListener.php line 176 {"exception":"[object] (TypeError(code: 0): array_filter() expects parameter 1 to be array, null given at /mnt/web302/b1/77/57048277/htdocs/contao/production/contao4/vendor/alpdesk/alpdesk-parallax/src/Listener/HooksListener.php:176)"} []`

**Comment by xprojects-de** [comment]
Jip danke! 

Fehler tritt/trat auf wenn man NUR im ContentElement einen AnimationEffekt zugeweisen hat und im Artikel keine Options (weder Parallax noch Animation) zugewiesen hat.

Ist gefixed und in Version 1.0.6 behoben. Ist bereits freigegeben!

Um ein kurzes Feedback wäre ich dankbar.

Danke und Grüße

**Comment by jankout** [comment]
Danke für die schnelle Fehlerbehung. Es läuft alles wie gewünscht. :-)
